apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o391icjnk-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a5a1db1ccf.gsqr.p3.openshiftapps.com/rhtap/rhtap-qe:c03a9d9fcfb90939cbe9abf8eb05b3cb76a5052b@sha256:5f1a7726bb03c02f3a2a58fd5298423d242f1e8a651514f6655af1f332a16374
          name: container-image
