apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o391icjnk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o391icjnk-python 
  name: o391icjnk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: o391icjnk-python 
